package com.houston.javaconfig;



/**
 * DO NOT EDIT THIS FILE!!!
 */
public final class Car {

	private Engine engine;
	
	public void setEngine(Engine engine) {
		this.engine = engine;
	}
	
	public Engine getEngine() {
		return engine;
	}
}
