package com.houston.javaconfig;

/**
 * DO NOT EDIT THIS FILE!!!
 */
public final class Engine {

	private final boolean fast;
	
	public Engine(boolean fast) {
		this.fast = fast;
	}

	public boolean isFast() {
		return fast;
	}
}
