package com.houston.javaconfig;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * DO NOT EDIT THIS FILE!!!
 */
public final class Garage {

	@Autowired(required=false)
	private Owner owner;
	
	private boolean destroyed;
	
	public boolean isOwned() {
		return owner != null;
	}
	
	public void destroy() {
		destroyed = true;
	}
	
	public boolean isDestroyed() {
		return destroyed;
	}
}
